### ISSUE TITLE
bind now requires an additional param

### ISSUE THREAD

**Issue by mrtizmo** [polyswarm/perigord#10]
They updated the library 2 weeks ago: https://github.com/ethereum/go-ethereum/tree/master/accounts/abi/bind

After I build my bindings, which are completely auto generated I am encountering an error with parameters/argument mismatches:

bindings/Foo.go:121:30: not enough arguments in call to
bind.NewBoundContract
    have (common.Address, abi.ABI, bind.ContractCaller,
bind.ContractTransactor)
    want (common.Address, abi.ABI, bind.ContractCaller,
bind.ContractTransactor, bind.ContractFilterer)

**Comment by mjkoo** [comment]
Resolved in a36f6901093c6fdcaf3107f319ab2ca2cd0408fe
