### ISSUE TITLE
errors when installing / building

### ISSUE THREAD

**Issue by asterix23** [polyswarm/perigord#11]
gsaxe2:~/Documents/crypto$ go get -u github.com/polyswarm/perigord/...
# github.com/polyswarm/perigord/migration/bindings
../../go/src/github.com/polyswarm/perigord/migration/bindings/Migrations.go:122:61: undefined: bind.ContractFilterer
../../go/src/github.com/polyswarm/perigord/migration/bindings/Migrations.go:131:118: undefined: bind.ContractFilterer
../../go/src/github.com/polyswarm/perigord/migration/bindings/Migrations.go:136:30: too many arguments in call to bind.NewBoundContract

**Comment by mjkoo** [comment]
It looks like you might be trying to install in a workspace with an older version of go-ethereum, try updating that or installing in a new workspace. The code in `master` should work with the latest go-ethereum. A TODO we have to address is versioning dependencies, but we haven't come to an agreement on how to best do that.
