### ISSUE TITLE
how to watch the event of contract

### ISSUE THREAD

**Issue by jkcomment** [polyswarm/perigord#12]
Hi!

I recently development dapp using Perigord. Perigord is cool and easy to understand.
BTW, I would like to watch the event of contract, but will someone tell me how to do it?

Thank you and best regards.

**Comment by mjkoo** [comment]
Hi, thanks for your interest in the project! An example of watching contract events can be found 
 in the WatchForEvents function in our main repo ( https://github.com/polyswarm/polyswarm/blob/2694baaaf5db2500400c6f94040c7ae81fbe5f11/bounty/registry.go#L138 )

**Comment by jkcomment** [comment]
Thank you. I will try it! :D
