### ISSUE TITLE
perigord deploy: no contract code at given address

### ISSUE THREAD

**Issue by quantonganh** [polyswarm/perigord#14]
Follow these:
- https://decentralize.today/introducing-perigord-golang-tools-for-ethereum-dapp-development-60556c2d9fd
- https://www.youtube.com/watch?v=oQZtKf_hzOU

Running `perigord deploy`, enter "blah":

```
Enter passphrase for account 0x945Cd603A6754cB13C3D61d8fe240990f86f9f8A:
Enter passphrase for account 0x945Cd603A6754cB13C3D61d8fe240990f86f9f8A:
Error: [no contract code at given address]
exit status 1
Error: [exit status 1]
```

Running `perigord test`:

```
Running migration 1
Enter passphrase for account 0x945Cd603A6754cB13C3D61d8fe240990f86f9f8A:
----------------------------------------------------------------------
FAIL: tests/Foo.go:26: foo_test.TestFoo

tests/Foo.go:28:
    c.Assert(session, NotNil)
... value = nil

Running migration 1
Enter passphrase for account 0x945Cd603A6754cB13C3D61d8fe240990f86f9f8A:
----------------------------------------------------------------------
FAIL: tests/TokenERC20.go:19: TokenERC20Suite.SetUpTest

tests/TokenERC20.go:22:
    c.Fatal(err)
... Error: authentication needed: password or unlock


----------------------------------------------------------------------
PANIC: tests/TokenERC20.go:33: TokenERC20Suite.TestName

... Panic: Fixture has panicked (see related PANIC)
OOPS: 0 passed, 2 FAILED, 1 MISSED
--- FAIL: Test (0.01s)
FAIL
exit status 1
FAIL	github.com/quantonganh/tokendapp	0.065s
Error: [exit status 1]
exit status 1
Error: [exit status 1]
```

Sure, default account has been unlocked:

```
> personal.unlockAccount(web3.eth.coinbase, "blah", 0)
true
```

What is the problem? Is there any configuration where I can config the passphrase for coinbase account?

**Comment by olliephillips** [comment]
I'm see similar when running "perigord test". 

```Error: authentication needed: password or unlock```

I'm on Mac.

To remedy, I've tried passing flag ```--unlock``` and ```--password``` with absolute path to ```etc/pw``` to like so:

```geth --unlock 0x945Cd603A6754cB13C3D61d8fe240990f86f9f8A --password $DIR/etc/pw --datadir $DIR --nodiscover --maxpeers 0 --mine --minerthreads 1 --rpc --rpcapi "eth,web3,personal,net" console```

No success and now a bit stuck. Any pointers appreciated.

**Comment by olliephillips** [comment]
For people seeing above, swap this line in your migration/test files:

```
network.UnlockWithPrompt(account)
```
for this one:

```
network.Unlock(account, "blah")
```
Oddly, you actually now get prompted to enter the passphrase, but hitting `enter` takes you past it and the tests, at least for me, complete successfully.

**Comment by myhndl** [comment]
Thank you for your report!

Sadly, Perigord is currently un-maintained. Closing this ticket so as to avoid cluttering various Projects.

SHOULD WE RESUME MAINTENANCE, RE-OPEN THIS TICKET.
