### ISSUE TITLE
Default generated migration file not working

### ISSUE THREAD

**Issue by frollo** [polyswarm/perigord#7]
If I try to run `perigord migrations` I get the following error:

    migrations/1_Migrations.go:20:35: cannot use 0 (type int) as type accounts.Account in argument to network.NewTransactor
    migrations/1_Migrations.go:38:35: cannot use 0 (type int) as type accounts.Account in argument to network.NewTransactor
    migrations/2_Foo.go:20:35: cannot use 0 (type int) as type accounts.Account in argument to network.NewTransactor
    migrations/2_Foo.go:38:35: cannot use 0 (type int) as type accounts.Account in argument to network.NewTransactor

This happens on a newly created project, out of `perigord init` as well as with any other project.
If it can be of any help, I'm working on macOS High Sierra.

## Steps to reproduce

The issue first presented itself when working on a new contract (following your [tutorial](https://decentralize.today/introducing-perigord-golang-tools-for-ethereum-dapp-development-60556c2d9fd)) but it happens as well on the default ones:

    mkdir newProj
    cd newProj
    perigord init
    perigord build
    perigord migrate

**Comment by frollo** [comment]
I've been working on it for a while and, while I haven't been able to resolve the issue, I'm posting what I've got so far, in case it will help.

As stated in the error messages I posted above, the issue resides in `network.NewTransactor` which now expects an `account.Account` instead of `uint` (the change happened on commit [ad2263b "Use keystores for deriving signers"](https://github.com/polyswarm/perigord/commit/ad2263b1150d3f25cb1ff041cb4095c021ed2984)). 

Since both calls to `network.NewTransactor` happen in an environment with a `network.Network`, which holds a list of `Account`'s I've tried to work around the issue using one of the elements of said list (which, still isn't working, but I think it's my fault). This, obviously, won't completely fix the issue, since any newly generated migration will still have the same problem, but it's a step toward the solution.

**Comment by mjkoo** [comment]
Thanks for the detailed bug report! This should be fixed as of 40d65f1bfccecfe662a8399d85761cb02bf18f25 . We changed the interface to enable loading in accounts from keystores to enable interaction with geth not just the simulated backend, and the migration template apparently escaped that update.

We will be updating the tutorial as well shortly, however it should still be largely accurate with the exception of needing to set a keystore path in perigord.yaml per network. I believe that this will resolve your issue of retrieving the accounts from the network.
