### ISSUE TITLE
Handle duplicate contract names

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/perigord#8]
Currently unsure what happens with the binding generator when two or more contracts in separate subdirectories of the contracts directory have the same name, last might overwrite all preceding. Figure out proper way to handle this, perhaps we need to generate different golang packages or something similar.

**Comment by myhndl** [comment]
Perigord is currently un-maintained. Closing this ticket so as to avoid cluttering various Projects.

SHOULD WE RESUME MAINTENANCE, RE-OPEN THIS TICKET.
